// ─────────────────────────────────────────────────────────────────────────────
// PluginProcessor.h — the "brain" of the plugin: DSP + parameters + state.
// A header DECLARES what exists; the matching .cpp DEFINES how it works.
// ─────────────────────────────────────────────────────────────────────────────
#pragma once            // Include this header only once per compile (no duplicates).
#include <JuceHeader.h> // Umbrella header generated by CMake; pulls in all of JUCE.

// Our processor IS-A juce::AudioProcessor. That base class is an "interface" the
// host (DAW / Standalone) calls into. It has pure-virtual functions (declared "= 0"
// in JUCE), so we MUST implement them all before we can create an instance.
//   final    -> nobody may subclass this further.
//   public   -> the section below is accessible from outside (the host needs it).
class DelayAudioProcessor final : public juce::AudioProcessor {
public:
  DelayAudioProcessor();                     // Constructor: sets up buses + parameters.
  ~DelayAudioProcessor() override = default; // Destructor: compiler-generated default.

  // ── Audio lifecycle ──────────────────────────────────────────────────────
  // Called by the host before audio starts (and on sample-rate/blocksize change).
  void prepareToPlay(double sampleRate, int samplesPerBlock) override;
  // Called when audio stops; free anything prepareToPlay allocated. (Empty here.)
  void releaseResources() override {}
  // THE audio loop. Runs hundreds of times/sec; must be fast and lock-free.
  void processBlock(juce::AudioBuffer<float>&, juce::MidiBuffer&) override;

  // ── Editor (GUI) ─────────────────────────────────────────────────────────
  juce::AudioProcessorEditor* createEditor() override; // Builds our window.
  bool hasEditor() const override { return true; }     // Yes, we have a UI.

  // ── Metadata the host queries (mostly boilerplate) ───────────────────────
  const juce::String getName() const override { return JucePlugin_Name; } // From PRODUCT_NAME.
  bool acceptsMidi() const override { return false; }
  bool producesMidi() const override { return false; }
  double getTailLengthSeconds() const override { return 0.0; } // No reverb/delay tail.

  // ── Legacy "programs" preset system — required, but we do nothing with it ──
  int getNumPrograms() override { return 1; } // Must be >= 1.
  int getCurrentProgram() override { return 0; }
  void setCurrentProgram(int) override {} // (int) = unnamed = "unused".
  const juce::String getProgramName(int) override { return {}; }
  void changeProgramName(int, const juce::String&) override {}

  // ── Save / restore state (session recall, presets) ───────────────────────
  void getStateInformation(juce::MemoryBlock& destData) override;       // Save.
  void setStateInformation(const void* data, int sizeInBytes) override; // Restore.

  // The parameter tree: thread-safe bridge between UI and audio thread. Public so
  // the editor can attach controls to it. Host automation & save/load use it too.
  juce::AudioProcessorValueTreeState apvts;

private:
  // Builds the list of parameters. static = belongs to the class, not an instance
  // (the constructor calls it while apvts is still being built).
  static juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout();

  // Forbids accidental copying of the processor + warns on leaks in debug builds.
  JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(DelayAudioProcessor)
};
